[parity]
chain = "demo-spec.json"
base_path = "./tmp/parity0"

[account]
unlock = ["0x004ec07d2329997267Ec62b4166639513386F32E"]
password = ["node.pwds"]

[network]
port = 30300

[rpc]
# hosts = ["192.168.1.107:8540,127.0.0.1:8540"]
# cors = "file://"
#interface = "10.13.0.15"
interface = "192.168.137.212"
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[websockets]
# interface = "all"
port = 8546

[ui]
force = true
disable = false
port = 8180

# [dapps]
# port = 8080

[mining]
engine_signer = "0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e"
reseal_on_txs = "none"
reseal_min_period = 5000
force_sealing = true
